image: gradle:8.6-jdk17

stages:
  - build

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: gradle-cache
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_debug_apk:
  stage: build
  script:
    - chmod +x ./gradlew || true
    - ./gradlew :app:assembleDebug
  artifacts:
    name: "A2Mobile-APK"
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 7 days
